"""A cheap model fixes grammar and readability. Nothing else, and it is checked.

The copy is generated by templates, so its failures are mechanical: a doubled
space where a field was empty, a comma splice, a sentence that reads as
assembled rather than written. A small model is good at exactly those and
costs a fraction of a cent.

It is also, unsupervised, good at helpfully improving a claim -- turning
"Google SWE Intern" into something rounder, adding a number that was not
there, warming a sentence with a conversation that never happened. So the
model's output is never trusted on its own. It proposes a revision; `verify`
decides whether it stayed inside grammar and readability, and a revision that
touched anything else is discarded whole and the original sent instead.

The model cannot add, only fail to change. Standard library only.
"""
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request

from .profile import ME, signature

ENDPOINT = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/") \
    + "/chat/completions"
MODEL = os.getenv("OUTREACH_POLISH_MODEL", "gpt-4.1-nano")

# Per million tokens, for reporting what a run cost. A stale number here makes
# a wrong report, never a wrong decision.
PRICES = {"gpt-4.1-nano": (0.10, 0.40), "gpt-4.1-mini": (0.40, 1.60),
          "gpt-5-nano": (0.05, 0.40), "gpt-5.4-nano": (0.05, 0.40),
          "gpt-4o-mini": (0.15, 0.60)}

# How far the length may move. A rewrite that grows is a rewrite that added
# something, whatever it says it did.
LENGTH_BAND = 0.20

SYSTEM = """You are a copy editor for one short email. Fix grammar, \
punctuation, spacing and awkward phrasing. Nothing else.

You MUST NOT:
- add, remove or alter any fact, name, company, job title, number, percentage, \
date, school, degree, GPA or URL
- add any sentence that introduces new information
- claim any prior contact, conversation or relationship
- reorder, merge, split or reword the bulleted lists -- copy every bullet \
across character for character
- change the greeting name or the sign-off
- change the meaning or the tone

You MAY: fix a doubled space, a missing or wrong comma, subject-verb \
agreement, a run-on or comma splice, a clumsy clause order, an inconsistent \
tense, a repeated word.

Most of the time the right answer is to change almost nothing. Returning the \
text unchanged is a correct and expected outcome. Never improve, strengthen or \
warm the writing.

Reply with JSON only: {"subject": "...", "body": "...", "notes": ["..."]} \
where notes names each fix in a few words."""

_URL = re.compile(r"https?://\S+")
# Numbers as they are written in the copy: 33%, 2%, $50K, 460, 500M+, 300K, 4.0
_NUM = re.compile(r"\$?\d[\d,.]*\s*[%KMB+]*")
_PROPER = re.compile(r"\b[A-Z][A-Za-z&.'-]+\b")
_WORD = re.compile(r"[a-z']+")

# The only words an edit may introduce. Fixing a run-on or an article genuinely
# needs one of these; nothing else does. A revision that brings in any other
# word brought in a thought, whatever the model called it -- "I am a huge
# admirer of your work here" adds no name, no number and no URL, sits well
# inside the length band, and is exactly the kind of warmth this must not add.
ADDABLE = frozenset("""
a an and as at but by for from in into of on or so that the then to with
is are was were be been being has have had do does did will would can could
i it its this these those there their they them he she his her we us our you
your which who whom while when where if not no nor than too very just also
""".split())


def immutable(subject: str, body: str, context: dict) -> list[str]:
    """Strings that must survive the edit character for character."""
    must = [context.get("company") or "", *(context.get("roles") or []),
            ME["name"], ME["school"], ME["degree"], ME["grad"],
            ME["portfolio"], ME["linkedin"]]
    if first := (context.get("first_name") or "").strip():
        must.append(f"Hi {first},")
    if m := re.match(r"\[([^\]]+)\]", subject):
        must.append(m.group(0))
    return [s for s in must if s]


def verify(subject: str, body: str, new_subject: str, new_body: str,
           context: dict) -> list[str]:
    """Why this revision may not be used, or [] if it may.

    Three questions, in order of how much damage the answer prevents: did
    anything that must not move, move; did anything appear that was not there
    before; and did the text grow. The second is the one that catches a model
    being helpful -- a number or a company name in the output that is absent
    from the input did not come from the email.
    """
    problems = []
    # Per field, not on the two joined together: "Tesla" surviving in the
    # subject said nothing about the body, where every mention had been
    # replaced with "the company".
    for token in immutable(subject, body, context):
        for label, was, now in (("subject", subject, new_subject),
                                ("body", body, new_body)):
            if was.count(token) and now.count(token) < was.count(token):
                problems.append(f"{label} dropped or altered: {token[:60]!r}")

    before, after = subject + "\n" + body, new_subject + "\n" + new_body
    added = {w for w in _WORD.findall(after.lower())} \
        - {w for w in _WORD.findall(before.lower())} - ADDABLE
    for word in sorted(added):
        problems.append(f"invented wording: {word!r}")
    for label, pattern in (("url", _URL), ("number", _NUM), ("name", _PROPER)):
        was = {m.strip() for m in pattern.findall(before)}
        now = {m.strip() for m in pattern.findall(after)}
        for added in sorted(now - was):
            problems.append(f"invented {label}: {added!r}")

    if abs(len(after) - len(before)) > LENGTH_BAND * len(before):
        problems.append(f"length moved {len(before)} -> {len(after)}")

    bullets = lambda t: [ln.strip() for ln in t.splitlines() if ln.startswith("  - ")]
    if bullets(body) != bullets(new_body):
        problems.append("bullet list changed")
    return problems


def polish(subject: str, body: str, context: dict) -> dict:
    """{subject, body, changed, rejected, notes, cost}.

    On any failure -- no key, HTTP error, unparseable answer, a revision that
    did not verify -- the original is returned unchanged. This runs on mail
    that is about to be sent, so the fallback has to be the text that was
    already reviewed and tested, never nothing and never a guess.
    """
    out = {"subject": subject, "body": body, "changed": False,
           "rejected": [], "notes": [], "cost": 0.0, "model": MODEL}
    key = os.getenv("OPENAI_API_KEY", "")
    if not key:
        out["rejected"] = ["OPENAI_API_KEY is not set"]
        return out

    payload = {"model": MODEL, "temperature": 0,
               "messages": [{"role": "system", "content": SYSTEM},
                            {"role": "user", "content":
                             f"SUBJECT\n{subject}\n\nBODY\n{body}"}],
               "response_format": {"type": "json_object"}}
    req = urllib.request.Request(
        ENDPOINT, data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json", "Authorization": "Bearer " + key})
    try:
        with urllib.request.urlopen(req, timeout=90) as r:
            data = json.loads(r.read())
        answer = json.loads(data["choices"][0]["message"]["content"])
        new_subject = str(answer["subject"]).strip()
        new_body = str(answer["body"])
    except urllib.error.HTTPError as exc:
        out["rejected"] = [f"HTTP {exc.code}: {exc.read()[:160].decode('utf-8','replace')}"]
        return out
    except Exception as exc:
        out["rejected"] = [f"{type(exc).__name__}: {exc}"]
        return out

    usage = data.get("usage") or {}
    cin, cout = PRICES.get(MODEL, (0.0, 0.0))
    out["cost"] = (usage.get("prompt_tokens", 0) * cin
                   + usage.get("completion_tokens", 0) * cout) / 1_000_000

    # The signature is rebuilt rather than accepted back, so no edit can reach
    # the one block that carries every link and the graduation year.
    sig = signature()
    if sig in body:
        new_body = new_body.split(sig)[0].rstrip() + "\n\n" + sig + "\n"

    if problems := verify(subject, body, new_subject, new_body, context):
        out["rejected"] = problems
        return out

    out.update(subject=new_subject, body=new_body,
               changed=(new_subject, new_body) != (subject, body),
               notes=[str(n) for n in (answer.get("notes") or [])])
    return out
