"""A cheap model fixes grammar and readability. Nothing else, and it is checked.

The copy is generated by templates, so its failures are mechanical: a doubled
space where a field was empty, a comma splice, a sentence that reads as
assembled rather than written. A small model is good at exactly those and costs
a fraction of a cent.

It is also, unsupervised, good at helpfully improving a claim -- turning
"Google SWE Intern" into something rounder, adding a number that was not there,
warming a sentence with a conversation that never happened. So the model's
output is never trusted on its own. It proposes a revision; `verify` decides
whether it stayed inside grammar and readability, and a revision that touched
anything else is discarded whole and the original sent instead.

The model cannot add, only fail to change. Standard library only.
"""
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request

from .profile import ME, signature

ENDPOINT = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/") \
    + "/chat/completions"
MODEL = os.getenv("OUTREACH_POLISH_MODEL", "gpt-4.1-nano")

# Per million tokens, for reporting what a run cost. A stale number here makes
# a wrong report, never a wrong decision.
PRICES = {"gpt-4.1-nano": (0.10, 0.40), "gpt-4.1-mini": (0.40, 1.60),
          "gpt-5-nano": (0.05, 0.40), "gpt-5.4-nano": (0.05, 0.40),
          "gpt-4o-mini": (0.15, 0.60)}

# How far the length may move. A rewrite that grows is a rewrite that added
# something, whatever it says it did.
LENGTH_BAND = 0.20

_URL = re.compile(r"https?://\S+")
# Numbers as they are written in the copy: 33%, 2%, $50K, 460, 500M+, 300K, 4.0
_NUM = re.compile(r"\$?\d[\d,.]*\s*[%KMB+]*")
_PROPER = re.compile(r"\b[A-Z][A-Za-z&.'-]+\b")
_WORD = re.compile(r"[a-z']+")

# The only words an edit may introduce. Fixing a run-on or an article genuinely
# needs one of these; nothing else does. A revision that brings in any other
# word brought in a thought, whatever the model called it -- "I am a huge
# admirer of your work here" adds no name, no number and no URL, sits well
# inside the length band, and is exactly the kind of warmth this must not add.
ADDABLE = frozenset("""
a an and as at but by for from in into of on or so that the then to with
is are was were be been being has have had do does did will would can could
i it its this these those there their they them he she his her we us our you
your which who whom while when where if not no nor than too very just also
""".split())


def _system() -> str:
    """The prompt, stating the rules `verify` actually enforces.

    Built from ADDABLE rather than describing it, so the prompt and the check
    cannot drift apart: a word added to one is a word the other already knows.
    Prose about "staying in scope" produced revisions rejected for reasons the
    model was never told, which is a wasted call every time.
    """
    return f"""You are a copy editor for one short email. Fix grammar, \
punctuation, spacing and awkward phrasing. Nothing else.

Your revision is checked mechanically before it is used and rejected whole if \
it breaks any of these. They are constraints, not guidance:

1. EVERY WORD in your output must already appear in the input. The only words \
you may introduce are: {' '.join(sorted(ADDABLE))}. If a fix would need any \
other new word, do not make that fix.
2. No number, percentage, amount, date or URL may appear that was not in the \
input, and none may be altered or dropped.
3. No name may appear that was not in the input -- no company, person, product \
or place.
4. Copy every bulleted line (those beginning with two spaces and a dash) across \
character for character. Do not reword, reorder, merge or split them.
5. Keep the greeting line, the sign-off and the signature block exactly as they \
are.
6. Your output must be within {int(LENGTH_BAND * 100)}% of the input's length.

So: no new claims, no added warmth, no invented prior contact, no strengthened \
wording. You are removing errors, not improving writing.

Most of the time the right answer is to change almost nothing. Returning the \
text unchanged is a correct and expected outcome.

Reply with JSON only: {{"subject": "...", "body": "...", "notes": ["..."]}} \
where notes names each fix in a few words."""


def immutable(subject: str, body: str, context: dict) -> list[str]:
    """Strings that must survive the edit character for character."""
    must = [context.get("company") or "", *(context.get("roles") or []),
            ME["name"], ME["school"], ME["degree"], ME["grad"],
            ME["portfolio"], ME["linkedin"]]
    if first := (context.get("first_name") or "").strip():
        must.append(f"Hi {first},")
    if m := re.match(r"\[([^\]]+)\]", subject):
        must.append(m.group(0))
    return [s for s in must if s]


def verify(subject: str, body: str, new_subject: str, new_body: str,
           context: dict) -> list[str]:
    """Why this revision may not be used, or [] if it may.

    Three questions, in order of how much damage the answer prevents: did
    anything that must not move, move; did anything appear that was not there
    before; and did the text grow. The second is the one that catches a model
    being helpful -- a number or a company name in the output that is absent
    from the input did not come from the email.
    """
    problems = []
    # Per field, not on the two joined together: "Tesla" surviving in the
    # subject said nothing about the body, where every mention had been
    # replaced with "the company".
    for token in immutable(subject, body, context):
        for label, was, now in (("subject", subject, new_subject),
                                ("body", body, new_body)):
            if was.count(token) and now.count(token) < was.count(token):
                problems.append(f"{label} dropped or altered: {token[:60]!r}")

    before, after = subject + "\n" + body, new_subject + "\n" + new_body
    for word in sorted({w for w in _WORD.findall(after.lower())}
                       - {w for w in _WORD.findall(before.lower())} - ADDABLE):
        problems.append(f"invented wording: {word!r}")
    for label, pattern in (("url", _URL), ("number", _NUM), ("name", _PROPER)):
        was = {m.strip() for m in pattern.findall(before)}
        now = {m.strip() for m in pattern.findall(after)}
        for added in sorted(now - was):
            problems.append(f"invented {label}: {added!r}")

    if abs(len(after) - len(before)) > LENGTH_BAND * len(before):
        problems.append(f"length moved {len(before)} -> {len(after)}")

    bullets = lambda t: [ln.strip() for ln in t.splitlines() if ln.startswith("  - ")]
    if bullets(body) != bullets(new_body):
        problems.append("bullet list changed")
    return problems


def _ask(messages: list, key: str) -> tuple[dict, str, float]:
    """One call. (answer, error, cost) -- exactly one of answer/error is real."""
    payload = {"model": MODEL, "temperature": 0, "messages": messages,
               "response_format": {"type": "json_object"}}
    data = None
    for _ in range(2):
        req = urllib.request.Request(
            ENDPOINT, data=json.dumps(payload).encode(),
            headers={"Content-Type": "application/json",
                     "Authorization": "Bearer " + key})
        try:
            with urllib.request.urlopen(req, timeout=90) as r:
                data = json.loads(r.read())
            break
        except urllib.error.HTTPError as exc:
            detail = exc.read()[:200].decode("utf-8", "replace")
            # Some newer models accept only the default temperature and reject
            # the request outright. Drop it and retry, rather than reporting a
            # model swap as an outage.
            if exc.code == 400 and "temperature" in detail \
                    and "temperature" in payload:
                payload.pop("temperature")
                continue
            return {}, f"HTTP {exc.code}: {detail}", 0.0
        except Exception as exc:
            return {}, f"{type(exc).__name__}: {exc}", 0.0
    if data is None:
        return {}, "temperature rejected twice", 0.0

    usage = data.get("usage") or {}
    cin, cout = PRICES.get(MODEL, (0.0, 0.0))
    cost = (usage.get("prompt_tokens", 0) * cin
            + usage.get("completion_tokens", 0) * cout) / 1_000_000
    try:
        answer = json.loads(data["choices"][0]["message"]["content"])
        return ({"subject": str(answer["subject"]).strip(),
                 "body": str(answer["body"]),
                 "notes": [str(n) for n in (answer.get("notes") or [])]},
                "", cost)
    except Exception:
        return {}, "editor returned no usable JSON", cost


def polish(subject: str, body: str, context: dict) -> dict:
    """{subject, body, changed, retried, rejected, notes, cost}.

    On any failure -- no key, HTTP error, unparseable answer, or a revision
    that did not verify twice -- the original is returned unchanged. This runs
    on mail about to be sent, so the fallback has to be the text that was
    already reviewed and tested, never nothing and never a guess.
    """
    out = {"subject": subject, "body": body, "changed": False, "retried": False,
           "rejected": [], "notes": [], "cost": 0.0, "model": MODEL}
    key = os.getenv("OPENAI_API_KEY", "")
    if not key:
        out["rejected"] = ["OPENAI_API_KEY is not set"]
        return out

    sig = signature()
    last: tuple[str, list[str]] | None = None
    cost = 0.0
    for attempt in range(2):
        messages = [{"role": "system", "content": _system()},
                    {"role": "user",
                     "content": f"SUBJECT\n{subject}\n\nBODY\n{body}"}]
        if last:
            # The checker's own words, fed back. A model told exactly which
            # rule it broke tends to return a smaller, valid edit; told
            # nothing, it returns the same one again and the call is wasted.
            messages += [
                {"role": "assistant", "content": last[0]},
                {"role": "user", "content":
                 "That revision was rejected: " + "; ".join(last[1])
                 + ". Return one that breaks none of the rules, or return the "
                   "text unchanged."}]

        answer, err, spent = _ask(messages, key)
        cost += spent
        if err:
            out["rejected"], out["cost"] = [err], cost
            return out

        new_subject, new_body = answer["subject"], answer["body"]
        # The signature is rebuilt rather than accepted back, so no edit can
        # reach the one block carrying every link and the graduation year.
        if sig in body:
            new_body = new_body.split(sig)[0].rstrip() + "\n\n" + sig + "\n"

        problems = verify(subject, body, new_subject, new_body, context)
        if not problems:
            out.update(subject=new_subject, body=new_body, notes=answer["notes"],
                       cost=cost, retried=attempt > 0,
                       changed=(new_subject, new_body) != (subject, body))
            return out
        last = (json.dumps({"subject": new_subject, "body": new_body}), problems)

    out["rejected"], out["cost"], out["retried"] = last[1], cost, True
    return out
